service: analysisV2

frameworkVersion: "3"

provider:
  name: aws
  region: ap-northeast-2
  ecr:
    images:
      appimage:
        path: ./

functions:
  anomally:
    image:
      name: appimage
    events:
      - http:
          path: anomal
          method: get
      - http:
          path: plot
          method: get
      - http:
          path: graph
          method: get
      - http:
          path: group
          method: get
      - http:
          path: csv/dates
          method: get
