service: analysisV2

frameworkVersion: "3"

provider:
  name: aws
  region: ap-northeast-2
  environment:
    sliceCsvTopicArn: ${self:custom.sliceCsvTopicArn}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sns:*"
          Resource:
            - "*"
  ecr:
    images:
      appimage:
        path: ./
custom:
  sliceCsvTopicArn: !Ref SliceTopic
functions:
  anomally:
    timeout: 30
    image:
      name: appimage
    events:
      - http:
          path: anomal
          method: get
      - http:
          path: plot
          method: get
      - http:
          path: graph
          method: get
      - http:
          path: group
          method: get
      - http:
          path: csv
          method: get
      - sns:
          arn: ${self:custom.sliceCsvTopicArn}
          topicName: sliceCsv-topic

resources:
  Resources:
    SliceTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: sliceCsv-topic

plugins:
  # swagger documentation
  - serverless-aws-documentation
